repos:
  - repo: https://github.com/LilSpazJoekp/docstrfmt
    rev: v1.6.1
    hooks:
      - id: docstrfmt
        language_version: python3
        exclude: "docs"


  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              pytest.xml|
              coverage.txt
          )$
      - id: check-added-large-files
        args: [ '--maxkb=700' ]
      - id: debug-statements
        language_version: python3
