name: code coverage

on:
  pull_request_target:
    branches:
      - master

jobs:
  code-coverage:
    runs-on: codeberg-small-lazy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install poetry
        run: |
          pipx install poetry
          echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies and build package
        run: |
          poetry install --with tests

      - name: Build coverage file
        run: |
          poetry run pytest --cov-config=pyproject.toml | tee pytest-coverage.txt
        env:
          NPSSO_CODE: ${{ secrets.NPSSO_CODE }}
          USER_NAME: ${{ vars.USER_NAME }}
          FRIEND_USER_NAME: ${{ vars.FRIEND_USER_NAME }}
          BLOCKED_USER_NAME: ${{ vars.BLOCKED_USER_NAME }}

      - name: Upload coverage reports to Codecov
        uses: https://github.com/codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
