name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  ci:
    runs-on: codeberg-tiny
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install poetry
        run: |
          pipx install poetry
          echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Get Tag Name
        id: get_and_remove_v_from_tag
        run: |
          TAG_NAME="${{ github.ref_name }}"
          TAG_NAME="${TAG_NAME:1}" # Remove the first character (leading 'v')
          echo "VERSION=${TAG_NAME}" >> $GITHUB_ENV

      - name: Build & Upload
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry version $VERSION
          poetry build
          poetry publish
