name: Pytest

on:
  pull_request_target:
    branches:
      - master

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    environment: ${{ inputs.environment }}
    strategy:
      matrix:
        os: [codeberg-tiny]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          pipx install poetry
          echo "/root/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies and build package
        run: poetry install --with tests

      - name: Test with pytest
        run: poetry run python pre_push.py -nu
        env:
          NPSSO_CODE: ${{ secrets.NPSSO_CODE }}
          USER_NAME: ${{ vars.USER_NAME }}
          FRIEND_USER_NAME: ${{ vars.FRIEND_USER_NAME }}
          BLOCKED_USER_NAME: ${{ vars.BLOCKED_USER_NAME }}
