name: code coverage
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      NPSSO_CODE:
        required: true

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  code-coverage-core:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies and build package
        run: |
          poetry install --with tests

      - name: Build coverage file
        run: |
          poetry run pytest --cov-config=pyproject.toml | tee pytest-coverage.txt
        env:
          NPSSO_CODE: ${{ secrets.NPSSO_CODE }}
          USER_NAME: ${{ vars.USER_NAME }}
          FRIEND_USER_NAME: ${{ vars.FRIEND_USER_NAME }}
          BLOCKED_USER_NAME: ${{ vars.BLOCKED_USER_NAME }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
